[package]
name = "ICMPv6RAFilter"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
env_logger = "0.11.5"
log = "0.4.22"
nfq = "0.2.5"
nftables = "0.5.0"
pnet = "0.35.0"
pnet_macros = "0.35.0"
pnet_macros_support = "0.35.0"