[package]
name = "IPv6PrefixFilter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
ctrlc = "3.4.5"
env_logger = "0.11.5"
ipnet = "2.10.1"
log = "0.4.22"
nfq = "0.2.5"
nftables = "0.5.0"
once_cell = "1.20.2"
pnet = "0.35.0"
pnet_macros = "0.35.0"
pnet_macros_support = "0.35.0"
thiserror = "2.0.3"
